# **Lab 5: Introduction to Web Scraping & Web Crawling**

## Part 1: Concepts

### Web Scraping vs Web Crawling

| Aspect | Web Scraping | Web Crawling |
|--------|-------------|-------------|
| Definition | **Extracting Specific data/content** from web pages | Automated browsing of websites to **find and collect links or pages** |
| Goal | Extract Structure data (e.g., prices, names) | Discover and index web pages |
| Output | Raw or Structured data (CSV, DataFrame) | A list or map of URLs (Site Structure) |
| Tools | BeautifulSoup, Selenium, Puppeteer | Scrapy (Spider), Search engine bots |
| Usage Example | Price Monitoring, data mining, sentiment Analysis | Build dataset for search engine |
| Scope | Narrow - Focuses on content from specific pages | Broad - looks at many pages |
| Frequency | Can be One-Time or Periodic | Often runs continuously (Like Crawlers) |

### Simple Explanation

* Scraping = “Give me this data from this page”
* Crawling = “Explore the website and collect links/data”

## Part 2: Scrape using Beautiful Soup

### Setup

In [76]:
# !pip install requests beautifulsoup4 pandas selenium webdriver-manager

### Import Libraries

In [77]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

### Define URL

In [78]:
URL_list = "http://quotes.toscrape.com/"

### Add Headers
**Why headers?**

Websites block bots. Headers make your request look like a browser.

In [79]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"
}

### Send Request

In [80]:
# Configure Selenium options
chrome_options = Options()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36")

# Initialize WebDriver
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)

driver.get(URL_list)
print("Status: Page successfully fetched via Selenium. Title:", driver.title)

### Parsing HTML with BeautifulSoup

In [81]:
soup = BeautifulSoup(driver.page_source, "html.parser")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Quotes to Scrape</title>
<link href="/static/bootstrap.min.css" rel="stylesheet"/>
<link href="/static/main.css" rel="stylesheet"/>
</head>
<body>
<div class="container">
<div class="row header-box">
<div class="col-md-8">
<h1>
<a href="/" style="text-decoration: none">Quotes to Scrape</a>
</h1>
</div>
<div class="col-md-4">
<p>
<a href="/login">Login</a>
</p>
</div>
</div>
<div class="row">
<div class="col-md-8">
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
<span>by <small class="author" itemprop="author">Albert Einstein</small>
<a href="/author/Albert-Einstein">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
<a class="tag" href="/tag/change/page/1/">change</a>
<a class="tag" href="/tag/deep-thoughts/page/1/">deep-thoughts</a>
<a class="tag" href="/tag/thinking/page/1/">thinking</a>
<a class="tag" href="/tag/world/page/1/">world</a>
</div>
</div>
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>
<span>by <small class="author" itemprop="author">J.K. Rowling</small>
<a href="/author/J-K-Rowling">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="abilities,choices" itemprop="keywords"/>
<a class="tag" href="/tag/abilities/page/1/">abilities</a>
<a class="tag" href="/tag/choices/page/1/">choices</a>
</div>
</div>
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>
<span>by <small class="author" itemprop="author">Albert Einstein</small>
<a href="/author/Albert-Einstein">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="inspirational,life,live,miracle,miracles" itemprop="keywords"/>
<a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
<a class="tag" href="/tag/life/page/1/">life</a>
<a class="tag" href="/tag/live/page/1/">live</a>
<a class="tag" href="/tag/miracle/page/1/">miracle</a>
<a class="tag" href="/tag/miracles/page/1/">miracles</a>
</div>
</div>
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>
<span>by <small class="author" itemprop="author">Jane Austen</small>
<a href="/author/Jane-Austen">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="aliteracy,books,classic,humor" itemprop="keywords"/>
<a class="tag" href="/tag/aliteracy/page/1/">aliteracy</a>
<a class="tag" href="/tag/books/page/1/">books</a>
<a class="tag" href="/tag/classic/page/1/">classic</a>
<a class="tag" href="/tag/humor/page/1/">humor</a>
</div>
</div>
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>
<span>by <small class="author" itemprop="author">Marilyn Monroe</small>
<a href="/author/Marilyn-Monroe">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="be-yourself,inspirational" itemprop="keywords"/>
<a class="tag" href="/tag/be-yourself/page/1/">be-yourself</a>
<a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
</div>
</div>
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>
<span>by <small class="author" itemprop="author">Albert Einstein</small>
<a href="/author/Albert-Einstein">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="adulthood,success,value" itemprop="keywords"/>
<a class="tag" href="/tag/adulthood/page/1/">adulthood</a>
<a class="tag" href="/tag/success/page/1/">success</a>
<a class="tag" href="/tag/value/page/1/">value</a>
</div>
</div>
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</span>
<span>by <small class="author" itemprop="author">André Gide</small>
<a href="/author/Andre-Gide">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="life,love" itemprop="keywords"/>
<a class="tag" href="/tag/life/page/1/">life</a>
<a class="tag" href="/tag/love/page/1/">love</a>
</div>
</div>
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“I have not failed. I've just found 10,000 ways that won't work.”</span>
<span>by <small class="author" itemprop="author">Thomas A. Edison</small>
<a href="/author/Thomas-A-Edison">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="edison,failure,inspirational,paraphrased" itemprop="keywords"/>
<a class="tag" href="/tag/edison/page/1/">edison</a>
<a class="tag" href="/tag/failure/page/1/">failure</a>
<a class="tag" href="/tag/inspirational/page/1/">inspirational</a>
<a class="tag" href="/tag/paraphrased/page/1/">paraphrased</a>
</div>
</div>
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“A woman is like a tea bag; you never know how strong it is until it's in hot water.”</span>
<span>by <small class="author" itemprop="author">Eleanor Roosevelt</small>
<a href="/author/Eleanor-Roosevelt">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="misattributed-eleanor-roosevelt" itemprop="keywords"/>
<a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">misattributed-eleanor-roosevelt</a>
</div>
</div>
<div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
<span class="text" itemprop="text">“A day without sunshine is like, you know, night.”</span>
<span>by <small class="author" itemprop="author">Steve Martin</small>
<a href="/author/Steve-Martin">(about)</a>
</span>
<div class="tags">
            Tags:
            <meta class="keywords" content="humor,obvious,simile" itemprop="keywords"/>
<a class="tag" href="/tag/humor/page/1/">humor</a>
<a class="tag" href="/tag/obvious/page/1/">obvious</a>
<a class="tag" href="/tag/simile/page/1/">simile</a>
</div>
</div>
<nav>
<ul class="pager">
<li class="next">
<a href="/page/2/">Next <span aria-hidden="true">→</span></a>
</li>
</ul>
</nav>
</div>
<div class="col-md-4 tags-box">
<h2>Top Ten tags</h2>
<span class="tag-item">
<a class="tag" href="/tag/love/" style="font-size: 28px">love</a>
</span>
<span class="tag-item">
<a class="tag" href="/tag/inspirational/" style="font-size: 26px">inspirational</a>
</span>
<span class="tag-item">
<a class="tag" href="/tag/life/" style="font-size: 26px">life</a>
</span>
<span class="tag-item">
<a class="tag" href="/tag/humor/" style="font-size: 24px">humor</a>
</span>
<span class="tag-item">
<a class="tag" href="/tag/books/" style="font-size: 22px">books</a>
</span>
<span class="tag-item">
<a class="tag" href="/tag/reading/" style="font-size: 14px">reading</a>
</span>
<span class="tag-item">
<a class="tag" href="/tag/friendship/" style="font-size: 10px">friendship</a>
</span>
<span class="tag-item">
<a class="tag" href="/tag/friends/" style="font-size: 8px">friends</a>
</span>
<span class="tag-item">
<a class="tag" href="/tag/truth/" style="font-size: 8px">truth</a>
</span>
<span class="tag-item">
<a class="tag" href="/tag/simile/" style="font-size: 6px">simile</a>
</span>
</div>
</div>
</div>
<footer class="footer">
<div class="container">
<p class="text-muted">
                Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
</p>
<p class="copyright">
                Made with <span class="zyte">❤</span> by <a class="zyte" href="https://www.zyte.com">Zyte</a>
</p>
</div>
</footer>
</body>
</html>

#### Extract Page Title

In [82]:
title = soup.find("h1").text.strip()
print(title)

Quotes to Scrape

### Extracting Data

#### Quote Text

In [83]:
quote = soup.find("div", class_="quote")
text = quote.find("span", class_="text").text

print(text)

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

#### Quote Author

In [84]:
quote = soup.find("div", class_="quote")
author = quote.find("small", class_="author").text

print(author)

Albert Einstein

#### Quote Tag

In [85]:
quote = soup.find("div", class_="quote")
tags = quote.find("div", class_="tags")
tag = tags.find("a", class_="tag").text

print(tag)

change

### Extract Whole Data

In [86]:
quotes = []

for q in soup.find_all("div", class_="quote"):
    text = q.find("span", class_="text").text
    author = q.find("small", class_="author").text
    tags = q.find("div", class_="tags")
    tag = [t.text for t in tags.find_all("a", class_="tag")]
    quotes.append({"Quote": text, "Author": author, "Tags": tag})

### Store Data in DataFrame

In [87]:
df = pd.DataFrame(quotes)
df.head()

,Quote,Author,Tags
0,“The world as we have created it is a process ...,Albert Einstein,"[change, deep-thoughts, thinking, world]"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"[abilities, choices]"
2,“There are only two ways to live your life. On...,Albert Einstein,"[inspirational, life, live, miracle, miracles]"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"[aliteracy, books, classic, humor]"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"[be-yourself, inspirational]"

### Scraping Stocks

In [88]:
URL_LIST = "https://stooq.com/q/?s=aapl.us"

In [89]:
driver.get(URL_LIST)
print("Status: Stock page successfully fetched via Selenium. Title:", driver.title)

In [90]:
soup = BeautifulSoup(driver.page_source, "html.parser")
soup

<html><head><meta content="text/html;charset=utf-8" http-equiv="content-type"/><meta content="apple inc, aapl.us, wykresy, wykres, dane, notowania, gieÅda, rynek" name="keywords"/><meta content="Wykresy notowaÅ spÃ³Åek, indeksÃ³w, kontraktÃ³w, walut, obligacji i towarÃ³w." name="description"/><title>AAPL.US (-0.29%) - Apple Inc - Stooq</title><script>function cpr(a,b){var c=0, f=document.f_c, n=8, s='';if(a){if(a.checked==true){if(b=='wig20'){f.r1.checked=true}else{f.r.value+=(f.r.value?' ':'')+b.toUpperCase()}}else{if(b=='wig20'){f.r1.checked=false}else{b=b.replace('^','\\^');f.r.value=(' '+f.r.value+' ').replace(new RegExp(' '+b+' ','i'),' ');f.r.value=f.r.value.substring(1,f.r.value.length-1)}}}if(f.r.value){t=f.r.value.split(' ');for(i=0;i<t.length;i++){ if(t[i].match('^[A-Za-z0-9._^]{2,16}$') && (!f.r1.checked || t[i]!='wig20')){ if(c++>=n) break; s+=t[i]+'+'; }}s=s.substring(0,s.length-1).toLowerCase();}if(f.r1.checked) s+=(s ? '+' : '')+f.r1.value;location.href='//stooq.com/q/?s=aapl.us&d=20260410&c=1d&t=l&a=lg'+(s ? '&r='+s : '');return false;}var f_s_,f_x,f_y;function f_a(a,b){var c;f_x=document.all?window.event.x+document.body.scrollLeft:a.pageX;f_y=document.all?window.event.y+document.body.scrollTop:a.pageY;if(window.XMLHttpRequest){c=new XMLHttpRequest();}else{if(window.ActiveXObject){try{c=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{c=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){}}}}c.onreadystatechange=function(){if(c.readyState==4 && c.status==200){var f=c.responseText.split('|');if(f[2]){$('f1').innerHTML='<a href=javascript:void(0) onclick=return(f_a(event,'+(b?'0))><span class=i2':'1))><span class=i1') +'></span></a>';$('f2').innerHTML='<a href=javascript:void(0) onclick=return(f_a(event,'+(b?'0))>Add to Favorites':'1))>Delete from Favorites') +'</span></a>';}f_i(1,[f[0],f[1]]);}};c.open('POST','//stooq.com/t/f/a/',true);c.setRequestHeader('Content-type','application/x-www-form-urlencoded');c.send('s=aapl.us'+(b?'&d=1':''));return false}function f_i(a,b){var a_=$('inf_a'),b_=$('inf_b');if(a){a_.style.display='none';b_.innerHTML=b[1];b_.style.backgroundColor='#'+b[0];a_.style.position='absolute';a_.style.display='block';a_.style.left=(f_x-b_.offsetWidth-50)+'px';a_.style.top=(f_y-b_.offsetHeight/2)+'px';clearTimeout(f_s_);f_s_=setTimeout(function(){f_i(0,0)},3000);}else{a_.style.display='none';}return false;}</script><script>var $=function(s){return document.getElementById(s)};!function(n,e,o){function t(n,e){return typeof n===e}function s(){var n,e,o,s,a,f,l;for(var c in i)if(i.hasOwnProperty(c)){if(n=[],e=i[c],e.name&&(n.push(e.name.toLowerCase()),e.options&&e.options.aliases&&e.options.aliases.length))for(o=0;o<e.options.aliases.length;o++)n.push(e.options.aliases[o].toLowerCase());for(s=t(e.fn,"function")?e.fn():e.fn,a=0;a<n.length;a++)f=n[a],l=f.split("."),1===l.length?Modernizr[l[0]]=s:(!Modernizr[l[0]]||Modernizr[l[0]]instanceof Boolean||(Modernizr[l[0]]=new Boolean(Modernizr[l[0]])),Modernizr[l[0]][l[1]]=s),r.push((s?"":"no-")+l.join("-"))}}var i=[],a={_version:"3.5.0",_config:{classPrefix:"",enableClasses:!0,enableJSClass:!0,usePrefixes:!0},_q:[],on:function(n,e){var o=this;setTimeout(function(){e(o[n])},0)},addTest:function(n,e,o){i.push({name:n,fn:e,options:o})},addAsyncTest:function(n){i.push({name:null,fn:n})}},Modernizr=function(){};Modernizr.prototype=a,Modernizr=new Modernizr,Modernizr.addTest("svg",!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect);var r=[];s(),delete a.addTest,delete a.addAsyncTest;for(var f=0;f<Modernizr._q.length;f++)Modernizr._q[f]();n.Modernizr=Modernizr}(window,document);(function(_){var z=_.document,y=-1,x=0;function a(){try{y=googlefc.getAllowAdsStatus()}catch(e){}if(y>-1){y&&b()?z.cookie="privacy="+Math.floor(new Date().getTime()/1000)+";expires="+new Date(Date.now()+2592000000).toUTCString()+";path=/":z.cookie="privacy=;expires=Thu, 01 Jan 1970 00:00:01 UTC;path=/";return}if(++x<5)setTimeout(a,5000)}function b(){var _=decodeURIComponent(z.cookie);return JSON.parse(_.substring(_.indexOf("FCCDCF=")+7).split(";",1))[3][1].length>150?1:0}_.addEventListener("load",a)})(window);(function(e){"use strict";function t(){this.data=Object.create?Object.create(null):{}}function r(e){return e.slice(0,1)==="_"?e+"~":e}function i(e){this.type=e;this.eventPhase=0;this.currentTarget=null;this.target=null}function s(){this.listeners=new t;return this}function o(e){setTimeout(function(){throw e},0)}function u(e,t){try{e(t)}catch(n){o(n)}}function d(){}function v(e){var t=Number(e);return t<1?1:t>18e6?18e6:t}function m(e,t){i.call(this,e);this.data=t.data}function g(){this.data=null}function y(e){e.onload=e.onerror=e.onprogress=e.onreadystatechange=d;e.abort()}function S(e,t){function H(){return N}function B(){if(N!==null){y(N);N=null}if(C!==0){clearTimeout(C);C=0}if(S!==0){clearTimeout(S);S=0}P=p;n.readyState=p}function j(){var e=1}function F(e){if(P!==p){if(a>d){a=d}C=setTimeout($,a);a=a*2+1;P=c;n.readyState=c;e.target=n;n.dispatchEvent(e);if(typeof n.onerror==="function"){n.onerror(e)}}}function I(){if(S!==0){clearTimeout(S);S=0}u(F,new i("error"))}function q(){S=0;z();if(x){x=false;S=setTimeout(q,g)}else{y(N);I()}}function R(e){if(P!==p){P=h;n.readyState=h;e.target=n;n.dispatchEvent(e);if(typeof n.onopen==="function"){n.onopen(e)}}}function U(e){if(P!==p){var t=String(e.type);e.target=n;n.dispatchEvent(e);if(t==="message"&&typeof n.onmessage==="function"){n.onmessage(e)}}}function z(){if(!A){var e="";try{e=N.getResponseHeader?N.getResponseHeader("Content-Type"):N.contentType}catch(t){o(t)}if(e&&w.test(e)){A=true;x=true;a=r;u(R,new i("open"))}}if(A&&P!==p){var n=N.responseText||"";var s=n.slice(L);if(s.length>0){x=true}if(_&&s.length>0){if(s.slice(0,1)==="\n"){s=s.slice(1)}_=false}var f=0;while((f=s.search(E))!==-1){var l=D.join("")+s.slice(0,f);D.length=0;if(s.length>f+1){s=s.slice(f+(s.slice(f,f+2)==="\r\n"?2:1))}else{if(s.slice(f,f+1)==="\r"){_=true}s=""}if(l){var c="";var h=l.indexOf(":");if(h!==-1){c=l.slice(h+(l.slice(h+1,h+2)===" "?2:1));l=l.slice(0,h)}if(l==="event"){M=c}if(l==="retry"){if(b.test(c)){r=v(c);a=r;if(d<r){d=r}}}if(l==="heartbeatTimeout"){if(b.test(c)){g=v(c);if(S!==0){clearTimeout(S);S=setTimeout(q,g)}}}if(l==="retryLimit"){if(b.test(c)){d=v(c)}}if(l==="data"){O.push(c)}}else{if(O.length!==0){u(U,new m(M||"message",{data:O.join("\n")}))}O.length=0;M=""}}if(s!==""){D.push(s)}L=n.length}}/*20251229 020239 <<<*//*function W(){z();if(A){var e=N.responseText||"";if(e.length>1024*1024){y(N);I()}}}*/function W(){z();var e=N.responseText||"";if(e.length>128*1024){y(N);I()}}/*>>> 20251229 020239*/function X(){z();I()}function V(){if(N.readyState===3){W()}}function $(){C=0;if(navigator.onLine===false){C=setTimeout($,500);return}N.onload=N.onerror=X;if(N.mozAnon===undefined){N.onprogress=W}N.onreadystatechange=V;x=false;S=setTimeout(q,g);L=0;A=false;O.length=0;M="";_=false;D.length=0;N.open("POST",/*e*/e.replace(/(\/\/aq)[0-9]{0,}(\.)/,"$1"+(Math.floor(Math.random()*aq_num_servers)+1)+"$2"),true);N.withCredentials=k;N.responseType="text";if(N.setRequestHeader){N.setRequestHeader("Content-type","application/x-www-form-urlencoded");N.setRequestHeader("Accept","text/event-stream");if(T!==""){}}N.send()}e=String(e);var n=this;var r=1e3;var a=r;var d=3e5;var g=45e3;var S=0;var x=false;var T="";var N=new l;var C=0;var k=Boolean(f&&t&&t.withCredentials);var L=0;var A=false;var O=[];var M="";var _=false;var D=[];var P=c;t=null;s.call(n);n.close=B;n.url=e;n.readyState=P;n.withCredentials=k;n.getXHR=H;$();return n}function x(){this.CONNECTING=c;this.OPEN=h;this.CLOSED=p}var n=Object.prototype.hasOwnProperty;t.prototype={data:null,get:function(e){var t=r(e);var i=this.data;return n.call(i,t)?i[t]:undefined},set:function(e,t){this.data[r(e)]=t},"delete":function(e){delete this.data[r(e)]}};i.CAPTURING_PHASE=1;i.AT_TARGET=2;i.BUBBLING_PHASE=3;i.prototype={type:"",eventPhase:0,currentTarget:null,target:null};s.prototype={listeners:null,hasListeners:function(e){return this.listeners.get(String(e))!==undefined},invokeEvent:function(e){var t=String(e.type);var n=e.eventPhase;var r=this.listeners;var s=r.get(t);if(!s){return}var u=s.length;var a=n===i.BUBBLING_PHASE?1:0;var f=n===i.CAPTURING_PHASE||n===i.BUBBLING_PHASE?2:1;while(a<u){e.currentTarget=this;var l=s[a];if(l!==null){try{l.call(this,e)}catch(c){o(c)}}e.currentTarget=null;a+=f}},dispatchEvent:function(e){e.eventPhase=i.AT_TARGET;this.invokeEvent(e)},addEventListener:function(e,t,n){e=String(e);n=Boolean(n);var r=this.listeners;var i=r.get(e);if(!i){r.set(e,i=[])}var s=i.length-(n?2:1);while(s>=0){if(i[s]===t){return}s-=2}i.push(n?t:null);i.push(n?null:t)},removeEventListener:function(e,t,n){e=String(e);n=Boolean(n);var r=this.listeners;var i=r.get(e);if(!i){return}var s=i.length;var o=[];var u=0;while(u<s){if(i[u+(n?0:1)]!==t){o.push(i[u]);o.push(i[u+1])}u+=2}if(o.length===0){r["delete"](e)}else{r.set(e,o)}}};var a=e.XMLHttpRequest;var f=Boolean(a&&e.ProgressEvent&&(new a).withCredentials!==undefined);var l=f?a:e.XDomainRequest;var c=0;var h=1;var p=2;g.prototype=i.prototype;m.prototype=new g;var b=/^\d+$/;var w=/^text\/event\-stream/i;var E=/[\r\n]/;x.prototype=s.prototype;S.prototype=new x;S.CONNECTING=c;S.OPEN=h;S.CLOSED=p;if(l){e.EventSource=S}})(this,aq_num_servers);var aq_, aq_a_;var aq_1_=0;var aq_m=1;var aq_s='';var aq_stp=0;var aq_num_servers=6;function aq_1(a){if(!a)return false;if(a.indexOf('+')<0)a=a.replace(/ /g,'+').replace(/(\+)([0-9]{1})/g,"$2$1").replace(/\+$/,'');if(a==aq_s)return false;if(aq_1_){aq_0();aq_1(a);return false}aq_s=a;aq_=new EventSource('//aq.stooq.com/?q='+a);aq_.addEventListener('open',function(e){aq_1_=1});aq_.addEventListener('message',function(e){var b; var c=e.data;if(aq_a_)clearTimeout(aq_a_);if(/*(b=c.indexOf('aqdat'))>-1 && c.substring(b).indexOf('|')>-1*/c.indexOf('|')>-1){aq(c,1);aq_chk_=1;c=''}});aq_.addEventListener('error',function(e){if(aq_m){aq_a_=setTimeout("aq_a(2)",30000);aq_1_=0}});return false}function aq_0(){aq_tck=Array();aq_tck_i=0;if(aq_)aq_.close();aq_1_=0;return false}var aq_tck=Array();var aq_tck_i=0;var aq_a_r=new Array();var cmp_h=0,cmp_n=0,cmp_t=1;function out(){document.out_formularz.submit()}function q_rdr(a,b){if(!cmp_f.s.value)return false;if(!a){var _,s;cmp_t=0;if(cmp_n<2){var t=$('cmp_n1').innerHTML.replace(/<[^>]*>|<[^<]*>/g,'');t=t.substring(0,t.indexOf('|')).replace('&amp;','&').toLowerCase();_=(cmp_h?cmp_h:'')+t;cmp_f.s.value=_;if($('cmp1a')&&cmp_f_.id=='cmp_f')$('cmp1a').value=_}setTimeout("q_rdr(1,"+(b?1:0)+")",60);return false;}else{if(b&&!cmp_fav){s=cmp_f.s.value;if(cmp_id2=='cmp_rs')return cmp_rs(s.replace(/[a-z]: {0,}/i,''));if(s.match(/^n:/i)){location.href='//stooq.com/q/n/?s='+s.replace(/n: {0,}| /i,'').toLowerCase();return false}else if(s.match(/^a:/i)){location.href='//stooq.com/q/a/?s='+s.replace(/a: {0,}| /i,'').toLowerCase();return false}else if(s.match(/^c:/i)){location.href='//stooq.com/q/c/?s='+s.replace(/c: {0,}| /i,'').toLowerCase();return false}else if(s.match(/^d:/i)){location.href='//stooq.com/q/d/?s='+s.replace(/d: {0,}| /i,'').toLowerCase();return false}else if(s.match(/^e:/i)){location.href='//stooq.com/q/e/?s='+s.replace(/e: {0,}| /i,'').toLowerCase();return false}else if(s.match(/^f:/i)){location.href='//stooq.com/q/f/?s='+s.replace(/f: {0,}| /i,'').toLowerCase();return false}else if(s.match(/^g:/i)){location.href='//stooq.com/q/g/?s='+s.replace(/g: {0,}| /i,'').toLowerCase();return false}else if(s.match(/^h:/i)){location.href='//stooq.com/q/h/?s='+s.replace(/h: {0,}| /i,'').toLowerCase();return false}else if(s.match(/^i:/i)){location.href='//stooq.com/q/i/?s='+s.replace(/i: {0,}| /i,'').toLowerCase();return false}else if(s.match(/^o:/i)){location.href='//stooq.com/q/m/?s='+s.replace(/m: {0,}| /i,'').toLowerCase();return false}else if(s.match(/^p:/i)){location.href='//stooq.com/q/p/?s='+s.replace(/p: {0,}| /i,'').toLowerCase();return false}else cmp_u(s);}else cmp_fav?f_a():cmp_u(cmp_f.s.value)}}cmp_b=new Array();cmp_e=cmp_aq_e='';cmp_i=cmp_aq_m=0;cmp_l='';cmp_fav=0;cmp_p=0;cmp_f=cmp_f_='';cmp_ph='';cmp_ex=0;cmp_id1=cmp_id1_=cmp_id2=cmp_id2_='';cmp_id1_s=new Array();aq_chk_=0;function cmp_a(a,b,c,d,e){if(d)cmp_ph=d;if(e)cmp_ex=e;if(a){if(!cmp_id1_s[b])cmp_id1_s[b]=$(b).innerHTML;cmp_f=$(a)?document.forms[a]:a;cmp_id1=b,cmp_id2=c;cmp_fav=b&&b.substring(5,9)=='_fav'?1:0}var f=0,g=0;clearTimeout(cmp_e);if(!cmp_f.s.value)f=1;if((cmp_h=cmp_f.s.value).match(/^a:|^c:|^d:|^e:|^f:|^g:|^h:|^i:|^n:|^o:|^p:/i)){if(cmp_h.length==2)f=1;cmp_h=cmp_h.substring(0,2);g=1}else cmp_h=0;if(f){$(cmp_id1).innerHTML=cmp_id1_s[cmp_id1]/*.style.display='none'*/;if(cmp_aq_m){if(cmp_aq_e)clearTimeout(cmp_aq_e); cmp_aq_e=setTimeout("cmp_aq()",1000);cmp_aq_m=0; }}if(cmp_t&&cmp_l!=(g?cmp_f.s.value.substring(2):cmp_f.s.value)){cmp_l=cmp_f.s.value.substring(cmp_h?2:0,100);if(cmp_l)cmp_q(cmp_l.replace('&','%26'))}if(cmp_id1_!=cmp_id1){if($(cmp_id1_)){$(cmp_id1_).style.display='none';$(cmp_id2_).innerHTML=''}if(cmp_f_){cmp_f_.s.value='';if($('cmp1a')&&cmp_f_.id=='cmp_f')$('cmp1a').value=''}cmp_id1_=cmp_id1;cmp_id2_=cmp_id2;cmp_f_=cmp_f}cmp_e=setTimeout("cmp_a()",25)}function cmp_c(){if(cmp_id1&&$(cmp_id1)&&$(cmp_id1).style.display=='block')$(cmp_id1).style.display='none'}function cmp_k(a,b){var _,b,d=$('cmp1a')&&b?1:0;cmp_i=1;if(a.keyCode==13){return q_rdr(0,1)}else if(a.keyCode==38){if(cmp_n){c='cmp_n'+cmp_n;$(c).style.backgroundColor='#fff'}cmp_n--;if(cmp_n<0)cmp_n=cmp_p;if(cmp_n){cmp_t=0;c='cmp_n'+cmp_n;$(c).style.backgroundColor='e9e9e9';var t=$(c).innerHTML.replace(/<[^>]*>|<[^<]*>/g,'');t=t.substring(0,t.indexOf('|')).replace('&amp;','&').toLowerCase();_=(cmp_h?cmp_h:'')+t;cmp_f.s.value=_;if(d)$('cmp1a').value=_}else{_=(cmp_h?cmp_h:'')+cmp_l;cmp_f.s.value=_;if(d)$('cmp1a').value=_}}else if(a.keyCode==40){if(cmp_n){c='cmp_n'+cmp_n;$(c).style.backgroundColor='#fff'}cmp_n++;if(cmp_n>cmp_p)cmp_n=0;if(cmp_n){cmp_t=0;c='cmp_n'+cmp_n;$(c).style.backgroundColor='e9e9e9';var t=$(c).innerHTML.replace(/<[^>]*>|<[^<]*>/g,'');t=t.substring(0,t.indexOf('|')).replace('&amp;','&').toLowerCase();_=(cmp_h?cmp_h:'')+t;cmp_f.s.value=_;if(d)$('cmp1a').value=_}else{_=(cmp_h?cmp_h:'')+cmp_l;cmp_f.s.value=_;if(d)$('cmp1a').value=_}}else cmp_t=1}function cmp_m(a){var _=(cmp_h?cmp_h:'')+a;cmp_f.s.value=_;if($('cmp1a')&&cmp_f_.id=='cmp_f')$('cmp1a').value=_;cmp_h?q_rdr(1,1):(cmp_id2=='cmp_rs'?cmp_rs(a):cmp_u(a));cmp_l=a}function cmp_o(a){var i,b;if(!cmp_i){cmp_t=0;b='cmp_n'+a;var t=$(b).innerHTML.replace(/<[^>]*>|<[^<]*>/g,'');t=t.substring(0,t.indexOf('|')).replace('&amp;','&').toLowerCase();cmp_f.s.value=(cmp_h?cmp_h:'')+t}for(i=1;i<=cmp_p;i++){if(i!=a){b='cmp_n'+i;$(b).style.backgroundColor='#fff'}}}function cmp_q(a){var b=document.getElementsByTagName('body')[0],c=$('cmp_id');if(c)b.removeChild(c);c=document.createElement('script');c.setAttribute('id','cmp_id');c.setAttribute('src','//stooq.com/cmp/?1775848499&q='+a+(cmp_ex?'&e':''));b.appendChild(c)}function cmp_u(a){location.href='//stooq.com/'+(cmp_ph?cmp_ph:'q/')+'?s='+a}function cmp_r(a){if(a)cmp_aq_m=1;$(cmp_id1).style.display=a?'block':'none';var b=a.split('|'),c='',d,d_;cmp_n=0;cmp_p=b.length;for(var k in b){d=b[k].split('~');k_='cmp_n'+(eval(k)+1);c+='<tr onclick=cmp_m(\''+(d_=d[0].replace(/<\/b>/g,'').replace(/<b>/g,'').toLowerCase())+'\') id='+k_+'><td nowrap><a href=q/?s='+d_+' onclick="return false">'+d[0]+'</a></td><td class=e1><span style=display:none>|</span>'+d[1]+'</td><td nowrap>&nbsp; '+(d[2]?d[2]:'')+'</td><td id=r nowrap>&nbsp; '+(d[3]&&d[3].indexOf('#')<0?'<span id='+'aq_'+d_+'_c'+d[5]+'>'+d[3]+'</span>':'')+'</td><td id=r nowrap>&nbsp;'+(d[4]?'<span id='+'aq_'+d_+'_m'+(d[4].indexOf('%')>-1?1:2)+'><font id=c'+((f=d[4].replace('%',''))>0?'1>+':(f<0?'2>':'3>'))+d[4]+'</font></span>':'')+'</td></tr>';if(cmp_fav)cmp_b[d_.replace('&amp;','&')]=[d[1],d[2]]}$(cmp_id2).innerHTML='<table width=100% border=0 cellpadding=2 cellspacing=0><tbody id=f13>'+c+'<tbody><tr><td colspan=5 align=right id=f11><a href=javascript:void(0)>Zamknij</a></td></tr></table>';if(cmp_aq_e)clearTimeout(cmp_aq_e);cmp_aq_e=setTimeout("cmp_aq()",4000);}function cmp_aq(){if(aq_chk_){/*aq_0();*/aq(0,0);s='';for(k in aq_tck){if(aq_a_r[k])aq_tck[k]=aq_a_r[k];s+=k+' '+aq_tck[k]}aq_1(s)}}function aq_r(a,b,c){if(b<0) return a;else a=eval(a).toFixed(b);if(c){var d,e;a+='';d=a.split('.');e=/(\d+)(\d{3})/;while(e.test(d[0])) d[0]=d[0].replace(e,'$1'+c+'$2');return d[0]+(b?'.'+((d[1]?d[1]:0)+Array(b).join(0)).substring(0,b):'')}return a}</script><style>:root{--aqtm:0.5s}html *{max-height:999999px}br{font-size:64%}#f22,.f22{font-size:139%}#f20,.f20{font-size:126%}#f19,.f19{font-size:118%}#f18,.f18{font-size:114%}#f16,.f16{font-size:101%}#f15,.f15{font-size:95%}#f14,.f14{font-size:90%}#f13,.f13{font-size:84%}#f13s{font-size:84%;line-height:135%}#f12,.f12{font-size:76%;font-family:arial,helvetica;line-height:122%}#f11{font-size:70%}#f10,.f10{font-size:64%;font-family:verdana,geneva,sans-seriff}#f10a{font-size:64%}#f09{font-size:58%;font-family:verdana,geneva,sans-seriff}#f03{font-size:20%}#f01{font-size:1%}#a{color:000000;font-size:64%;font-family:verdana,geneva,sans-seriff}#g1{color:#999}#ll,.ll{color:8888ee}#ll:visited,.ll:visited{color:9977aa}#c1{color:116611}#c2{color:ee0000}#c3{color:000000}#c4{color:666666}@keyframes aqup{0%{background:#d0ffd0}99%{background:#d0ffd0}100%{background:transparent}}@keyframes aqdw{0%{background:#ffd0d0}99%{background:#ffd0d0}100%{background:transparent}}#t01{background-color:ffffff}#t02,.t02{background-color:e9e9e9}#t03{background-color:f3f3f3}.tb1{border:solid 1px #cccccc}#s01{font-size:76%}#r,.r{text-align:right}#l,.l{text-align:left}#c,.c{text-align:center}#p_t1{background-color:f3f3f3;margin:0 4;padding:8 10}#spc1{font-weight:bold}.e1{max-width:350px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.e2{max-width:75px;overflow:hidden;text-overflow:ellipsis}.el0{opacity:50%}.el0.ela{opacity:100%}.el0.ela .el1{display:none}.el0.ela .el2{display:inline}.el2{display:none}.google-revocation-link-placeholder{display:none}.text_ll{font-size:142%}.text{font-size:86%}.text_s{font-size:75%}.text_ss{font-size:68%}@keyframes kle635v2{0%{opacity:0}90%{opacity:0}95%{opacity:1}100%{opacity:1}}@-webkit-keyframes kle635v2{0%{opacity:0}99%{opacity:0}100%{opacity:1}}</style><base href="https://stooq.com/"/><link href="/favicon.ico" icon="" rel="shortcut"/><link href="/apple-touch-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/><link href="/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/><link href="/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/><link href="/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/><link href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAMAAAAKE/YAAAAC61BMVEX//////v7//f3//Pz/+/v/+vr/+fn/+Pj/9vb/9fX/9PT/8vL/8PD/7+//7e3/7Oz/6+v/6ur/6en/5+f/5ub/5eX/5OT/4uL/4eH/4OD/3t7/3Nz/2tr/19f/1dX/0tL/z8//zc3/zMz/ysr+ysr/yMj/x8f/xsb/xcX/xMT/wcH/wMD/u7v/ubn/t7f/tLT/s7P/sbH/sLD/rKz/q6v/qan/qKj/paX/o6P/np7/nZ3/mpr/mZn/mJj/l5f/lJT/kZH/kJD/j4//jo7/i4v/iIj/hob/goL/fn7/fHz/enr/eHj/dHT/cnL/cXH/b2//bW3/Z2f/ZWX/YWH/YGD/X1//XV3/XFz/W1v/WFj/V1f/VVX/VFT/UlL/UVH/T0//TU3/S0v/Skr/SEj/RET/QkL/PDz/Ojr/ODj/Njb/NDT/MjL/MDD/Li7/LCz/Kyv/KSn/Jib/JCT/IiL/ICD/Hh7/HR3/Gxv/GBj/Fhb/FBT/ERH/DQ3/Cgr/CAj/BAT/AABUVFRTU1NSUlJRUVFPT09KSkpFRUVAQEA9PT06Ojo4ODg1NTU0NDQzMzMyMjIxMTEsLCwqKiopKSknJyckJCQiIiIgICAfHx8eHh4dHR0aGhoZGRkWFhYUFBQSEhIQEBAODg4NDQ0MDAwKCgoICAgHBwcGBgYFBQUDAwMBAQEAAABXV1daWlpcXFxeXl5hYWFkZGRnZ2doaGhra2tubm5ycnJ0dHR2dnZ7e3t+fn5/f3+AgICDg4OGhoaHh4eIiIiLi4uPj4+Tk5OVlZWZmZmgoKChoaGkpKSlpaWnp6etra2xsbGysrK1tbW2tra5ubm6urq+vr7BwcHFxcXIyMjMzMzNzc3Ozs7Pz8/Q0NDR0dHS0tLV1dXW1tbY2Njb29ve3t7g4ODi4uLj4+Pl5eXm5ubn5+fo6Ojq6urr6+vs7Ozt7e3u7u7w8PDz8/P09PT19fX29vb39/f4+Pj5+fn6+vr8/Pz9/f08LQXbAAAISklEQVR4Ae3Zf3QM5x7H8c/mBytJtaUlQgOqGqCKEtqiRSgtpbcArYoEIZrWlbAr86jKrxuqKhQIQrLZR3NRctFqSaVAlRBoSwkUyAqwfzbNznqeTWZ35JwxR+55Xv/JOXLe+e53njM7A0EQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEH4/+AVENikY/c+/Qe806/3q+0a1fE3oPLuXzt3bH/e9twtudt

In [91]:
title = soup.find("title").text
print("Title:", title)
clean_title = str(title).split("-")[-2].strip()
print("Clean Title:", clean_title)

Title: AAPL.US (-0.29%) - Apple Inc - Stooq
Clean Title: Apple Inc

In [92]:
tables = soup.find_all("table")
print("Number of tables found:", len(tables))

table = soup.find("table", {"id": "t1"})

rows = table.find_all("tr")
print("Number of rows in the table:", len(rows))

data = {}

for row in rows:
    tds = row.find_all("td")

    for td in tds:
        # 🔹 Extract label (first visible text)
        label = td.get_text(separator="\n").split("\n")[0].strip()

        # 🔹 Extract value from span (if exists)
        span = td.find("span")

        if span:
            value = span.get_text(strip=True)

            # Store only meaningful labels
            if label and value:
                data[label] = value

data

Number of tables found: 57
Number of rows in the table: 21

{'Last': '259.7400',
 'Date': '2026-04-10',
 'Rates of Return': '260.4900',
 'Change': '-0.7500',
 'High/Low': '262.1900',
 '52W Change': '+70.1460',
 'Open': '259.9400',
 'Prev.': '260.4900',
 'Bid': '259.7300',
 'Ask': '259.7400',
 'Volume': '10.7m',
 'Turnover': '2.8g',
 'No. Trades': '59 589'}

In [93]:
date = data.get("Date")
change_value = data.get("52W Change")
volume_value = data.get("Volume")
bid_value = data.get("Bid")
trades_number = data.get("No. Trades")

print("Date:", date)
print("52W Change:", change_value)
print("Volume:", volume_value)
print("Bid:", bid_value)
print("No. of Trades:", trades_number)

Date: 2026-04-10
52W Change: +70.1460
Volume: 10.7m
Bid: 259.7300
No. of Trades: 59 589

In [94]:
df = pd.DataFrame(
    {
        "Title": [clean_title],
        "Date": [date],
        "52W Change": [change_value],
        "Volume": [volume_value],
        "Bid": [bid_value],
        "No. Trades": [trades_number],
    }
)

In [95]:
df

       Title        Date 52W Change Volume       Bid No. Trades
0  Apple Inc  2026-04-10   +70.1460  10.7m  259.7300     59 589

# Comparisons between Tools of Scraping

| Feature | BeautifulSoup | Selenium |
|--------|--------------|----------|
| Speed | Fast | Slow |
| JavaScript | No | Yes |
| Browser | No | Yes |
| Difficulty | Easy | Medium |

### When to Use
- Use BeautifulSoup for static pages
- Use Selenium for dynamic pages

In [ ]:
soup_stock = BeautifulSoup(driver.page_source, "html.parser")
print(soup_stock.prettify()[:1000]) # Print first 1000 characters of prettified HTML to avoid huge output

In [ ]:
# Teardown
driver.quit()

In [ ]:
soup_stock = BeautifulSoup(driver.page_source, "html.parser")
print(soup_stock.prettify()[:1000]) # Print first 1000 characters of prettified HTML to avoid huge output

In [ ]:
# Teardown
driver.quit()